# Generated by Django 3.0.7 on 2021-12-18 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title not available', max_length=250)),
                ('description', models.CharField(blank=True, default='Description not available', max_length=600, null=True)),
                ('publishedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_url', models.URLField(max_length=300, unique=True)),
            ],
        ),
    ]
